# 텐서 (Tensor)
* tensor는 배열(array)나 행렬(matrix)와 매우 유사한 특수 자료구조로, Pytorch에서는 텐서를 이용하여 모델의 입출력, 모델의 매개변수 부호화 가능
* 텐서는 다른 GPU나 다른 하드웨어 가속기에서 실행 가능하다는 점만 제외하면 Numpy의 ndarray와 유사
* 자동미분에 최적화
* ndarray에 익숙하다면 Tensor API를 바로 사용 가능

In [1]:
import torch
import numpy as np

## 텐서(Tensor) 초기화
### 1. 데이터로부터 직접 생성
* `tocrch.tensor(data)`
* 데이터의 자료형 (data type)은 자동으로 유추

In [2]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

## 2. Numpy
* `torch.from_numpy(data)`
* Numpy array <-> Tensor 가능 (다만, Tensor -> Numpy는 Bridge 사용)

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

## 3. 다른 텐서로부터 생성하기
* `torch.ones_like(data)`: data의 **속성 유지** 하면서 tensor 내의 원소가 모두 1.
* `torch.rand_like(data, dtype = torch.float)` : 명시적으로 재정의해주면서 data의 **속성 덮어쓰기** & tensor 내의 원소가 random.
* 명시적으로 재정의(override)하지 않는다면, 인자로 주어진 텐서의 속성(**모양(shape), 자료형(dataype))을 유지


In [4]:
x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data, dtype = torch.float)

print(f"Ones Tensor: \n {x_ones} \n")
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.2892, 0.4216],
        [0.2702, 0.0280]]) 



### 4. 무작위(random) 또는 상수(constant) 값을 사용하기
* `shape`:텐서의 차원(dimension)을 나타내는 tuple, 아래 함수들에서는 출력 텐서의 차원의 결정


In [5]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8035, 0.4497, 0.3714],
        [0.1724, 0.3923, 0.9878]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 텐서의 속성 (Attribute)

* 텐서의 모양(shape)
* 텐서의 자료형 (datatype)
* 텐서가 저장되는 장치

In [6]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Tensor Operation
[연산 method 리스트 확인](https://pytorch.org/docs/stable/torch.html)

* 각 연산들은 GPU에서 실행 가능
* **Colab의 수정 > 노트 설정에서 GPU 할당 가능**
* 기본적으로 텐서는 CPU에 생성되지만, `.to` 메소드를 사용해서 (GPU availability 확인 후) GPU로 텐서를 명시적으로 이동 가능
* 단, 장치들 간 큰 텐서들을 복사하면 시간과 메모리가 많이 소요됨

In [7]:
# GPU가 존재하면 텐서 이동
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [8]:
torch.cuda.is_available()

True

### Numpy 식의 표준 인덱싱 & 슬라이싱


In [15]:
tensor = torch.ones(4,4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:,0]}")
print(f"Last column: {tensor[...,-1]}")

tensor[:,1] = 0 # 두 번째 열의 원소를 다 0으로 바꾸기
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### 텐서 합치기
* `torch.cat`: 주어진 차원에 따라 일련의 텐서 연결
* `torch.stack`: 새로운 차원을 따라 일련의 텐서를 연결 (이때 텐서들은 같은 사이즈여야 함, 차원의 추가)

In [23]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1)
print(t1.shape)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
torch.Size([4, 12])


In [22]:
t2 = torch.stack([tensor, tensor, tensor], dim = 1)
print(t2)
print(t2.shape)

tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])
torch.Size([4, 3, 4])


### 산술 연산 (Arithmetic Operations)
* 텐서끼리 더하기

In [11]:
tensor1 = torch.rand(shape)
tensor2 = torch.rand(shape)
tensor3 = torch.add(tensor1, tensor2)

print(f"tensor1: \n {tensor1} \n")
print(f"tensor2: \n {tensor2} \n")
print(f"tensor1 + tensor2: \n{tensor3} \n")

tensor1: 
 tensor([[0.1737, 0.5303, 0.4105],
        [0.5988, 0.4312, 0.3051]]) 

tensor2: 
 tensor([[0.3481, 0.0295, 0.1695],
        [0.6787, 0.3670, 0.1951]]) 

tensor1 + tensor2: 
tensor([[0.5218, 0.5598, 0.5800],
        [1.2775, 0.7982, 0.5001]]) 



* 두 텐서 간의 행렬 곱 (@)

In [31]:
# 두 텐서 간의 행렬 곱 (matrix multiplication) 계산
# y1 = y2 = y3
y1 = tensor@tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)

torch.matmul(tensor, tensor.T, out = y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [32]:
# 요소별 곱(element-wise product) 계산
# z1 = z2 = z3
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)

torch.mul(tensor, tensor, out = z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

### 단일요소 (single-element) 텐서
* 텐서의 모든 값을 하나로 집계(aggregate)하여 요소가 하나인 텐서의 경우, `item()`을 사용하여 Python 숫자 값으로 변환 가능


In [34]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [33]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


### 바꿔치기(in-place) 연산
* 연산 결과를 피연산자(operand)에 저장하는 연산으로, `_` 접미사를 가진다.
* 메모리 절약 가능 but derivative 계산에 문제 발생 가능

In [36]:
# x.copy_(y)나 x.t_()는 x를 변경한다.
print(f"{tensor} \n")
tensor.add_(5) # in_place로 5 더하기
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])


# Numpy 변환 (Bridge)
* CPU 상의 텐서와 Numpy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경
## 텐서를 NumPy 배열로 변환하기
`tensor.numpy()`

In [37]:
t = torch.ones(5)
print(f"t:\n{t}")
n = t.numpy()
print(f"n:\n{n}")

t:
tensor([1., 1., 1., 1., 1.])
n:
[1. 1. 1. 1. 1.]


In [38]:
# 텐서의 변경 사항이 NumPy 배열에 반영될 수 있다.
t.add_(1)
print(f"t: /n{t}")
print(f"n: \n{n}")

t: /ntensor([2., 2., 2., 2., 2.])
n: 
[2. 2. 2. 2. 2.]


## NumPy 배열을 텐서로 변환하기

In [39]:
n = np.ones(5)
t = torch.from_numpy(n)

In [40]:
# NumPy 배얼의 변경 사항이 텐서에 반영
np.add(n,1, out = n)
print(f"t : \n {t}")
print(f"n: \n{n}")

t : 
 tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: 
[2. 2. 2. 2. 2.]
